version: '3.8'

services:
  #defectivegoods.mvc:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=https://+:443;http://+:80
  #  ports:
  #    - "80"
  #    - "443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      
  dg.pgsql:
    ports:
        - 5434:5432
    environment:
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=dg
        - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
        - ./docker/temp/db:/var/lib/postgresql/data/pgdata