version: '3.4'

services:
  defectivegoods.mvc:
    image: defectivegoodsmvc:dev
    container_name: DefectiveGoods.Mvc
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DefectiveGoods.Mvc"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_defectivegoods.mvc$
    volumes:
      - C:\Users\4ymai\Desktop\C# and etc\DG\DefectiveGoods.Mvc:/app
      - C:\Users\4ymai\Desktop\C# and etc\DG:/src
      - C:\Users\4ymai\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_defectivegoods.mvc$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_defectivegoods.mvc$ \"/app/bin/Debug/net5.0/DefectiveGoods.Mvc.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true